### PR TITLE
Update readme changes

### PR DESCRIPTION
**Pull request by DuFF14**
Updated Changes.md to reflect recent changes. Updated Readme.md to provide link to documentation, as requested in Unity Asset Store submission feedback.

### CODE REVIEW

**Comment by DuFF14** [comment]
Unity Asset Store asks for "a full documentation file or a readme file that tells users where to find your online documentation." Do you think a link to the repo Readme will suffice? Is there a more appropriate link? 
Once this is merged, I will resubmit the package to the Asset Store.

**Comment by rpavlik** [comment]
Well, I think that's the best we have so far, though it's not ideal.

**Comment by rpavlik** [comment]
How hard is updating once we submit? Curious if you should be waiting until after I get some changes in.

**Comment by DuFF14** [comment]
It's not hard to update, just uploading the .unitypackage. It might take a week for an update to be approved/processed.

**Comment by rpavlik** [comment]
ah, so that's a pain. What about from the user end - how easy to update to a new version to an asset you got from the store?

**Comment by DuFF14** [comment]
Easy. Just hitting an update button from the download manager, and it shows you which files have changed. You can select which files you want to import.

**Comment by rpavlik** [comment]
OK, so at least there's that, that's OK.  Then I think it's probably OK to send in the current version.

**Comment by DuFF14** [comment]
Hmm, that Readme doesn't get included in the unitypackage, so I will add it manually for this upload.

**Comment by rpavlik** [comment]
oh, it's supposed to? Then that's easy to do - just edit the build script, it's the only editor script we have.

**Pull request merged**
