### PR TITLE
Added num_displays field to json config files and DeviceDescriptor.

### PR DESCRIPTION
**Pull request by DuFF14**
Added updated json config files for Sensics HMDs.
Updated camera projection matrix to accommodate HMDs with multiple displays.

### CODE REVIEW

**Comment by DuFF14** [comment]
Removed Json files and updated DisplayInterface.cs to retrieve Json config data from /display path.
Getting an error that Unity is not able to find dlls the first time it runs. It works every time except the first time after opening the project.

**Comment by yboger** [comment]
Need to also updated the readme.md file at OSVR-Unity/OSVR-Unity/Assets/OSVRUnity/Displays/README.md (or where it needs to be now) to account for these new parameters. Also need to make sure Oculus descriptor is also updated

**Comment by DuFF14** [comment]
Fixed the DllNotFoundException...
http://answers.unity3d.com/questions/283734/dllnotfoundexception-only-on-first-run.html

**Comment by DuFF14** [comment]
I removed the Displays folder, including the README.md. 

1) Should it remain there if no Json files remain in the Unity project?
The formatting for that file seems to be wonky...
https://github.com/OSVR/OSVR-Unity/blob/master/OSVR-Unity/Assets/OSVRUnity/Displays/README.md

2) Does the Oculus descriptor belong in the same folder as the others configs (https://github.com/OSVR/OSVR-Core/tree/master/apps/displays)?

3) Or are you asking me to add the new num_displays field to the file in the Oculus repo? (https://github.com/OSVR/OSVR-Oculus-Rift/blob/master/com_osvr_OculusRift.json) ?

**Comment by yboger** [comment]
Oculus JSON should be part of same folder just like any other HMD

**Comment by JeroMiya** [comment]
If you remove the display json files from OSVR-Unity, can we move them to their own repository? I found them very useful for emulating various screens in OSVR-MonoGame and just to see how the values vary from device to device. Thanks!

**Comment by DuFF14** [comment]
The display json files are in the OSVR-Core repo already: https://github.com/OSVR/OSVR-Core/tree/master/apps/displays

**Comment by rpavlik** [comment]
Closing this, as it was merged in only slightly modified form in #46

**Pull request closed without merging**
