### PR TITLE
Jero miya adapters

### PR DESCRIPTION
**Pull request by DuFF14**
Adding to @JeroMiya's pull request. Fixed some null refs and missing paths in devscene.unity.
Removed prefabs in devscene.unity that did not have a path and seemed superfluous.
Minor modifications to other scenes -- fixed a missing material, added a light where there was none.
Removed opengoggles from all ClientKit app ids.

### CODE REVIEW

**Comment by rpavlik** [comment]
Looks nice in a visual review, testing now. In general, just a couple quick notes:

- we don't actually own osvr.org sadly (though we do have getosvr.org whose main domain which bounces to osvr.github.io) - so the convention has been to use com.osvr.subproject.whatever where an ID is required.
- Unity is warning about inconsistent line endings. Make sure you have your Git set to "checkout and commit as is" - I'll see if there are things I can do (editorconfig and gitattributes) to enforce that better in the repo.
- I think the purpose of devscene is generally to be the place that the prefabs come from, so that was why I had (once upon a time) put prefabs there without paths. The unity dev/test workflow is still a little awkward/unfamiliar to me.

**Comment by DuFF14** [comment]
* Ah, I almost changed it to com instead of org. Let me know if you want me to make that change.
* Thought I had set that at some point, here is an example gitattributes that can be added to the repo to enforce this: http://superuser.com/questions/882691/atlassian-sourcetree-how-to-change-line-endings-globally
* I think the demo scenes could use an overhaul soon to make everything more clear. Seems like multiple scenes demonstrate the same things. I generally work in OSVRDemo2 (because I usually only have an HMD and no controllers) or OSVRDemo.

**Comment by rpavlik** [comment]
Yeah, or at least some docs on what's what to guide development. You can clearly see the parts I worked on when I just had a Hydra, or a hydra and a head tracker :)

Patches accepted ;)

**Comment by rpavlik** [comment]
Oh, also - are there any files in there that have to remain DOS line endings despite looking text-like? I'd think not, since Unity supports Mac OS X, but worth asking.

**Comment by DuFF14** [comment]
Yea I don't think so.

**Comment by rpavlik** [comment]
OK, fixed line endings, added gitattributes, and fixed all the names to be `com.osvr.osvr-unity.something`

@DuFF14 Can you go back and add back the prefabs without a path to the dev scene in the prefab prototype area? I am not sure how you'd edit them without having them in a scene like that.  Once that's done, go ahead and merge this - thanks!

**Pull request merged**
