### PR TITLE
Distortion

### PR DESCRIPTION
**Pull request by DuFF14**
Added Distortion effect. Will work with Unity 4 Pro or Unity 5 (free or pro).
Will look further into free workarounds, but this works for now...

### CODE REVIEW

**Comment by rpavlik** [comment]
I'm guessing from the apparently overlapping commits that this request depends on #24?

**Comment by rpavlik** [comment]
Oh, and what happens if you use this on unity 4 free? Any way we can easily "gracefully degrade" to no distortion shader in that case?

**Comment by DuFF14** [comment]
My first pull request should address the rolling issue, though I don't have an HMD to test that at the moment.

If Unity 4 free is being used, it will simply not use distortion. It shouldn't crash. It will show a warning or error in the debug console, but tracking will still work.

**Comment by rpavlik** [comment]
Once I merge this please update the news file to describe the Unity 4 free limitations.

**Pull request merged**
