### PR TITLE
Unity5 refactor

### PR DESCRIPTION
**Pull request by DuFF14**
Should be a clean upgrade to Unity5 now.
Fixed VRHead and VReye to compensate for overlap and roll, but need a dSight to test on. Looks correct.
Added the Newtonsoft DLL to plugins folder and removed SimpleJSON, modified parsing code in DeviceDescriptor to match.
VRDisplayTracked prefab will use HDK descriptor by default.

### CODE REVIEW

**Comment by rpavlik** [comment]
So does this work with Unity 4.6.x still? Does the same package work with both versions?

(The CI nodes currently have 4.6 licenses)

**Comment by DuFF14** [comment]
Works with both.

**Comment by rpavlik** [comment]
Can you add a changes file (like the one in OSVR core) that explains any changes that may affect how people use the package, and in particular upgrade?

**Comment by DuFF14** [comment]
Done. Will keep the changes file updated in future commits.

**Pull request merged**
