### PR TITLE
Unity Native VR Support

### PR DESCRIPTION
**Pull request by DuFF14**
This PR connects Unity's native VR support to OSVR-RenderManager, allowing OSVR-Unity apps to take advantage of Unity's VR optimizations such as "single-pass" rendering.

There is a new scene (OSVR-UnityVR-Demo.unity) and prefab (OsvrUnityStereoCameraParent). The new prefab is meant to replace VRDisplayTracked prefab as the VR camera in the scene.

To add OSVR support to an existing Unity VR app, you'd just add OsvrUnityNativeVR.cs to the Camera and add the "Split Stereo Display (non-head-mounted)" option to the list of supported VR SDKs in Player Settings.

This has been tested with Unity 2017 and HDK2 with this [direct mode enabled config file.](https://gist.github.com/DuFF14/097911834b89503ea7c8b5cc08108f40)
This may not support overfill/oversample correctly yet.

Here is a [unitypackage ](https://drive.google.com/file/d/0B0X-T5b2-zcOenFCalJpTUFxWG8/view?usp=sharing) of this PR, for testing.

### CODE REVIEW

**Comment by DuFF14** [comment]
Here is a profiler comparison of a test with the Palace Demo, which shows that rendering time is about cut in half.

**Comment by DuFF14** [comment]
Here is a unitypackage of this PR: https://drive.google.com/file/d/0B0X-T5b2-zcOenFCalJpTUFxWG8/view?usp=sharing

**Comment by russell-taylor** [comment]
Awesome!

**Comment by demonixis** [comment]
Does it work on Linux and Mac too?

**Comment by DuFF14** [comment]
@demonixis no, this doesn't add Linux or Mac support,

**Comment by Sp4iK** [comment]
Hi DuFF14, this is great. I've tested it a bit and it works okay, you just have to be sure to be running osvr server before entering play mode or Unity crashes, even if you tick "autostart server" it will start it but make Unity crash.

**Comment by DuFF14** [comment]
@Sp4iK Thanks! That should be fixed with the last commit. The previous commit added Android support.

**Pull request merged**
